# Generated by Django 2.1.5 on 2021-04-12 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('level', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('Verem', 'Stack'), ('Sor', 'Queue'), ('Csatolt Lista', 'Linked List')], max_length=200, null=True)),
                ('score', models.IntegerField(default=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
