# Generated by Django 2.1.5 on 2021-04-12 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('practices', '0002_auto_20210412_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Megoldas alatt', 'Megoldas alatt'), ('Megoldva', 'Megoldva'), ('Lepontozva', 'Lepontozva')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practices.Exercise')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Student')),
            ],
        ),
    ]
