# Generated by Django 3.0 on 2021-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0003_solving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solving',
            name='student',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Verem', 'Verem'), ('Sor', 'Sor'), ('Csatolt Lista', 'Csatolt Lista')], max_length=200, null=True),
        ),
    ]
