# Generated by Django 3.0 on 2021-06-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210526_1809'),
        ('practices', '0005_auto_20210607_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solving',
            name='exercise',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='practices.Exercise'),
        ),
        migrations.RemoveField(
            model_name='solving',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='solving',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
