# Generated by Django 3.0 on 2021-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210526_1809'),
        ('practices', '0006_auto_20210607_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solving',
            name='exercise',
        ),
        migrations.AddField(
            model_name='solving',
            name='exercise',
            field=models.ManyToManyField(null=True, to='practices.Exercise'),
        ),
        migrations.RemoveField(
            model_name='solving',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='solving',
            name='user_profile',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
