# Generated by Django 3.0 on 2021-06-08 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0007_auto_20210607_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
