# Generated by Django 3.0 on 2021-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0011_auto_20210609_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='solving',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solving',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
