# Generated by Django 3.0 on 2021-06-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0014_auto_20210616_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Verem', 'Verem'), ('Sor', 'Sor'), ('Csatolt Lista', 'Csatolt Lista'), ('Mohó algoritmus', 'Mohó algoritmus'), ('Rekurzió', 'Rekurzió'), ('Dinamikus programozás', 'Dinamikus programozás'), ('Visszalépéses keresés', 'Visszalépéses keresés'), ('Gráfok', 'Gráfok')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('Könnyű', 'Könnyű'), ('Közepes', 'Közepes'), ('Nehéz', 'Nehéz')], max_length=200, null=True),
        ),
    ]
