# Generated by Django 3.0 on 2021-06-22 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0016_auto_20210622_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solving',
            name='score',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)]),
        ),
    ]
