# Generated by Django 3.0 on 2021-06-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0018_auto_20210623_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solving',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
