# Generated by Django 3.0 on 2021-06-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0019_auto_20210623_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solving',
            name='status',
        ),
    ]
